# Generated by Django 4.2.4 on 2023-09-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.CharField(default='default_image_url.jpg', max_length=200),
        ),
    ]
