# Generated by Django 4.2.4 on 2023-09-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_category_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.CharField(default='bed_sets.jpg', max_length=200),
        ),
    ]
