# Generated by Django 4.2.4 on 2023-09-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_category_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='overlay_image_url',
            field=models.CharField(default='overlay_bedroom.png', max_length=200),
        ),
    ]
