# Generated by Django 4.2.4 on 2023-09-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_category_overlay_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='overlay_image_url',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category_images/bed_sets.jpg', upload_to='category_images'),
        ),
        migrations.AddField(
            model_name='category',
            name='overlay_image',
            field=models.ImageField(default='category_images/bed_sets.png', upload_to='category_images'),
        ),
    ]
