# Generated by Django 4.2.4 on 2023-09-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_category_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='overlay_image',
            field=models.ImageField(default='category_images/overlay_bedroom.png', upload_to='category_images'),
        ),
    ]
