# Generated by Django 4.2.4 on 2023-09-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_cartitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='item_images/king_bed.jpg', upload_to='static/item_images'),
        ),
    ]
